import type { NextPage } from 'next'
import Head from 'next/head'
import Main from '../components/Content/Main'
import Header from '../components/Header/Header'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tasktime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossOrigin="anonymous"></link>
        <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet"></link>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ=" crossOrigin="anonymous"></script>
      </Head>
      <div className="bg-black-alt font-sans leading-normal tracking-normal">
        
            <Header/>

            <Main/>
      </div>

    </div>
  )
}

export default Home
